name: shazam
description: A music recognition app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  acr_cloud_sdk: ^2.0.0
  avatar_glow: ^2.0.1
  provider: ^5.0.0
  eva_icons_flutter: ^3.0.0
  font_awesome_flutter: ^9.0.0
  flutter_hooks: ^0.17.0
  hooks_riverpod: ^0.14.0+4
  audioplayers: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
     - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins.ttf

    - family: Monteserat
      fonts:
        - asset: assets/fonts/Monteserat.ttf


